### ISSUE TITLE
APK not running "flutter build apk --release"

### ISSUE THREAD

**Issue by eleomilagrosa** [pion/ion-app-flutter#10]
to replicate just
use this repo then run "Flutter build apk --release"

in debug it is working properly
but when I tried it building it to release

the app wont run at all.
is there additional configuration for released apps?

> [√] Flutter (Channel master, 1.19.0-2.0.pre, on Microsoft Windows [Version 10.0.17763.1217], locale en-US)
> • Flutter version 1.19.0-2.0.pre at C:\flutter
> • Framework revision 721927efd3 (4 weeks ago), 2020-05-21 17:52:02 -0700
> • Engine revision 9ce1e5c5c7
> • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android SDK at C:\Users\Eleo\AppData\Local\Android\sdk
> • Platform android-R, build-tools 29.0.2
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
> • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.5)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 39.0.3
> • Dart plugin version 191.8423
> • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] VS Code (version 1.45.1)
> • VS Code at C:\Users\Eleo\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.11.0
> 
> [√] Connected device (3 available)
> • SM G988B • R5CN20CC82P • android-arm64 • Android 10 (API 29)
> • Web Server • web-server • web-javascript • Flutter Tools
> • Chrome • chrome • web-javascript • Google Chrome 83.0.4103.106

**Comment by cloudwebrtc** [comment]
Please try to modify this commit
https://github.com/cloudwebrtc/flutter-webrtc-demo/commit/ea5b122c77b5bd6124dad74dc06cef74c198d3e8

**Comment by eleomilagrosa** [comment]
tnx this should be in ReadMe
